spring.config.import=optional:file:.env[.properties]
spring.application.name=api-gateway
server.port=${PORT}
# Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}

# Routes
spring.cloud.gateway.routes[0].id=quantity-service
spring.cloud.gateway.routes[0].uri=lb://quantity-measurement-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/quantity/**

spring.cloud.gateway.routes[1].id=auth-service
spring.cloud.gateway.routes[1].uri=lb://auth-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/auth/**
